language: cpp

compiler:
    - clang
    - gcc

before_script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew update && brew install lcov); fi
    - gem install coveralls-lcov

script:
    - mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=coverage && make
    - ctest -V

after_success:
    - cd build
    - lcov -c -d . -o cov.txt
    - lcov -e cov.txt "*/regtools/src/*" -o coverage.run.filtered.1
    - lcov -r coverage.run.filtered.1 "*src/utils/*" "*/tests/*" -o coverage.run.filtered
    - coveralls-lcov coverage.run.filtered

os:
    - linux
    - osx

jobs:
    include:
        - osx_image: xcode12.5

notifications:
    email:
        on_failure: always
        on_success: change
